"use client";
import{useState,useEffect,useCallback}from'react';import{ShieldCheck,Scale,Building2,FileCheck2,RefreshCw,Plus,ExternalLink,Copy,Clock3}from'lucide-react';
import{Button}from'@/components/ui/button';import{Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription}from'@/components/ui/dialog';import{Tabs,TabsList,TabsTrigger,TabsContent}from'@/components/ui/tabs';import{Select,SelectTrigger,SelectValue,SelectContent,SelectItem}from'@/components/ui/select';import{Table,TableHeader,TableHead,TableRow,TableBody,TableCell}from'@/components/ui/table';import{Input}from'@/components/ui/input';import{Textarea}from'@/components/ui/textarea';import{Toaster,toast}from'sonner';
import{actions,available,type Action}from'@/lib/actions';import{getRegistry,send,receipt,receiptState,deployment,short,safeLink,type Registry}from'@/lib/genlayer';
const label=(v:string)=>v.replaceAll('_',' ');const stamp=(t:number)=>t?new Date(t*1000).toLocaleString():'—';const longFields=['policy_text','scope','statement','response','reason'];
const limits:Record<string,number>={name:120,title:180,policy_text:12000,scope:2000,statement:2000,response:2000,reason:2000,expected_hash:64,website:500,policy_url:500,source_url:500};
type Tx={hash:string;method:string;status:string;time:string;error?:string};
export default function Home(){
 const[data,setData]=useState<Registry|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[updated,setUpdated]=useState(''),[id,setId]=useState(''),[sender,setSender]=useState(''),[senderInput,setSenderInput]=useState(''),[senderOpen,setSenderOpen]=useState(false),[action,setAction]=useState<Action|null>(null),[fields,setFields]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[txs,setTxs]=useState<Tx[]>([]),[now,setNow]=useState(0);
 const load=useCallback(async()=>{setLoading(true);try{const x=await getRegistry();setData(x);setError('');setUpdated(new Date().toLocaleTimeString());setId(v=>v||x.checks.at(-1)?.id||'')}catch(e:any){setError(e.message||'Could not read Studionet')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();setNow(Math.floor(Date.now()/1000));const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),1000);try{const a=sessionStorage.getItem('policyproof-account')||'';if(/^0x[\da-f]{40}$/i.test(a))setSender(a);const t=JSON.parse(localStorage.getItem('policyproof-transactions')||'[]');if(Array.isArray(t))setTxs(t.filter(t=>/^0x[\da-f]{64}$/i.test(t.hash)).slice(0,20))}catch{}return()=>clearInterval(timer)},[load]);
 const save=(n:Tx[])=>{setTxs(n);try{localStorage.setItem('policyproof-transactions',JSON.stringify(n))}catch{}};
 const current=data?.checks.find(c=>c.id===id);const org=(oid:string)=>data?.organizations.find(o=>o.id===oid);const policy=(pid:string)=>data?.policies.find(p=>p.id===pid);
 const open=(method:string,initial:Record<string,string>={})=>{setAction(actions.find(a=>a.method===method)!);setFields({check_id:id,expected_hash:'',...initial})};
 const selectSender=(a:string)=>{if(!/^0x[\da-f]{40}$/i.test(a)){toast.error('Enter a valid Studio account address');return}setSender(a.toLowerCase());sessionStorage.setItem('policyproof-account',a.toLowerCase());setSenderOpen(false)};
 const generate=()=>selectSender('0x'+Array.from(crypto.getRandomValues(new Uint8Array(20)),x=>x.toString(16).padStart(2,'0')).join(''));
 const recheck=async(tx:Tx)=>{try{const r=await receipt(tx.hash);const status=receiptState(r);setTxs(old=>{const n=old.map(x=>x.hash===tx.hash?{...x,status,error:status==='EXECUTION_FAILED'?'Finalized contract execution failed. Check receipt before retrying.':''}:x);try{localStorage.setItem('policyproof-transactions',JSON.stringify(n))}catch{}return n});if(status==='FINALIZED'){toast.success(`${label(tx.method)} finalized`);await load()}else if(status==='EXECUTION_FAILED')toast.error('Finalized execution failed');return['FINALIZED','EXECUTION_FAILED','UNDETERMINED','CANCELED','LEADER_TIMEOUT','VALIDATORS_TIMEOUT'].includes(status)}catch(e:any){toast.error(e.message||'Receipt unavailable. Use Recheck receipt before submitting again.');return true}};
 const gate=action?available(action.method,data?.checks.find(c=>c.id===fields.check_id),sender,now):{enabled:true,reason:''};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!action)return;if(!sender){setSenderOpen(true);return}if(!gate.enabled)return;setBusy(true);try{const hash=await send(action.method,action.fields.map(f=>(fields[f]||'').trim()),sender);if(!/^0x[\da-f]{64}$/i.test(hash))throw Error('Unexpected transaction hash');const tx={hash,method:action.method,status:'PENDING',time:new Date().toISOString()};save([tx,...txs].slice(0,20));setAction(null);toast.message('Submitted. Waiting for finalized execution.');for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,2000));if(await recheck(tx))break}}catch(e:any){toast.error(e.message||'Submission failed. Check receipt before retrying.')}finally{setBusy(false)}};
 return <main className="workspace"><Toaster richColors/><header><a className="brand" href="/"><ShieldCheck/>PolicyProof</a><nav><a href="https://github.com/amzar1st/PolicyProof" target="_blank" rel="noreferrer">Source <ExternalLink size={14}/></a><span className="network">Studionet · 61999</span><Button variant="outline" onClick={()=>{setSenderInput(sender);setSenderOpen(true)}}>{sender?short(sender):'Studio account'}</Button></nav></header>
 <section className="mast"><div><p className="eyebrow">COMPLIANCE REGISTER</p><h1>Policy is a promise.<br/><span>Proof makes it accountable.</span></h1><p>Compare published policies with public evidence. Inspect the reasoning, challenge a verdict, and follow the finalized record.</p></div><div className="seal"><ShieldCheck size={46}/><strong>Evidence → Consensus → Attestation</strong><span>Immutable policies. Transparent decisions.</span></div></section>
 <section className="metrics">{[[Building2,'Organizations',data?.counts.organizations],[FileCheck2,'Policy versions',data?.counts.policies],[Scale,'Compliance checks',data?.counts.checks]].map(([Icon,title,value]:any)=><div key={title}><Icon size={20}/><strong>{value??'—'}</strong><span>{title}</span></div>)}</section>
 <div className="liveline"><span>{loading?'Reading finalized state…':error?'Live read unavailable':`Finalized contract state · updated ${updated}`}</span><Button variant="ghost" size="sm" disabled={loading} onClick={load}><RefreshCw size={15}/>Refresh</Button></div>{error&&<div className="alert" role="alert"><strong>Could not refresh live records</strong><p>{error}. {data?'Last successful records remain visible.':'No sample data is substituted.'}</p></div>}
 <Tabs defaultValue="checks"><div className="toolbar"><TabsList variant="line"><TabsTrigger value="checks">Checks</TabsTrigger><TabsTrigger value="policies">Policies</TabsTrigger><TabsTrigger value="organizations">Organizations</TabsTrigger><TabsTrigger value="transactions">Transactions</TabsTrigger></TabsList><div><Button variant="outline" onClick={()=>open('create_organization')}><Plus size={15}/>Organization</Button><Button onClick={()=>open('open_compliance_check')}><Plus size={15}/>Compliance check</Button></div></div>
 <TabsContent value="checks"><div className="checkgrid"><section className="panel checklist"><div className="panelhead"><div><p className="eyebrow">ON-CHAIN REGISTER</p><h2>Compliance checks</h2></div><span className="badge">{data?.counts.checks??'—'}</span></div>{!data?.checks.length?<div className="empty"><FileCheck2/><h3>No checks to display</h3><p>Publish a policy, then open a check.</p></div>:data.checks.slice().reverse().map(c=><button className={'checkcard '+(id===c.id?'active':'')} key={c.id} onClick={()=>setId(c.id)}><div><code>{c.id}</code><span className={'badge '+(c.attestation?'final':'')}>{label(c.status)}</span></div><h3>{org(c.organization_id)?.name||c.organization_id}</h3><p>{policy(c.policy_id)?.title||c.policy_id}</p><footer>{c.review?label(c.review.verdict):'Awaiting evidence and review'}<Clock3 size={14}/></footer></button>)}</section>
 <section className="panel checkdetail">{current?<><div className="panelhead"><div><p className="eyebrow">{current.id} · {current.policy_id}</p><h2>{org(current.organization_id)?.name}</h2></div><span className={'badge '+(current.attestation?'final':'')}>{current.attestation?'ATTESTATION':label(current.status)}</span></div><div className="detailbody"><p className="eyebrow">CHECK SCOPE</p><p className="scope">{current.scope}</p><div className="deadlinegrid">{[['Evidence closes',current.evidence_deadline],['Challenge closes',current.challenge_deadline],['Resolution expires',current.expires_at]].map(([title,t]:any)=><div key={title}><span>{title}</span><strong>{stamp(t)}</strong>{t>now&&<small>{Math.floor((t-now)/60)}m {(t-now)%60}s remaining</small>}</div>)}</div>
 {current.review&&<div className={'verdict '+(current.attestation?'good':'')}><div><Scale size={20}/><h3>{label(current.review.verdict)}</h3><span className="badge">{current.status==='FINALIZED'?'FINAL':'PROVISIONAL'}</span></div><p>{current.review.reasoning}</p>{current.review.citations.map((u:string)=><a key={u} className="sourcelink" href={safeLink(u)} target="_blank" rel="noreferrer">{u}<ExternalLink size={13}/></a>)}{current.review.failed_urls.length>0&&<p className="failure">Unavailable or mismatched evidence: {current.review.failed_urls.join(', ')}</p>}</div>}
 {current.attestation&&<div className="attestation"><ShieldCheck size={26}/><div><strong>{current.attestation.id}</strong><p>Issued {stamp(current.attestation.issued_at)}. Applies only to this policy version and scope.</p><code>{current.attestation.policy_sha256}</code></div></div>}
 <div className="actionrow">{actions.slice(3).map(a=>{const g=available(a.method,current,sender,now);return <Button size="sm" variant={['validator_review','finalize'].includes(a.method)?'default':'outline'} key={a.method} disabled={busy||!g.enabled} title={g.enabled?a.help:g.reason} onClick={()=>open(a.method)}>{a.title}</Button>})}</div>{!sender&&<p className="hint">Select a Studio development account to submit evidence or a response.</p>}
 <div className="evidencegrid">{['requester','organization'].map(side=><div key={side}><h3>{side==='requester'?'Requester evidence':'Organization response'}</h3><p className="hint">{current.evidence[side].length} entries · 4 initial + 2 challenge slots</p>{current.evidence[side].length?current.evidence[side].map((e:any,i:number)=><div className="evidence" key={i}><a href={safeLink(e.url)} target="_blank" rel="noreferrer">{e.url} <ExternalLink size={13}/></a><p>{e.statement}</p><small>{stamp(e.submitted_at)}{e.challenge?' · challenge':''}</small>{e.expected_hash&&<code>{e.expected_hash}</code>}</div>):<p className="hint">No evidence submitted.</p>}</div>)}</div>
 {current.challenged&&<div className="note"><strong>Challenge on record</strong><p>{current.challenge_reason}</p></div>}<details><summary>Immutable policy and review audit trail</summary><h3>{policy(current.policy_id)?.title}</h3><p>{policy(current.policy_id)?.text}</p><code>{policy(current.policy_id)?.text_sha256}</code><p>Owner: <code>{current.owner}</code><br/>Requester: <code>{current.requester}</code></p>{current.history.map((r:any,i:number)=><div className="audit" key={i}><strong>Review {i+1} · {label(r.verdict)} · {stamp(r.reviewed_at)}</strong><p>{r.reasoning}</p>{r.snapshots.map((s:any,j:number)=><p className="hint" key={j}>{s.url}<br/><code>{s.text_sha256}</code></p>)}</div>)}</details></div></>:<div className="empty"><Scale/><h3>Select a check</h3><p>Evidence, deadlines, and validator reasoning appear here.</p></div>}</section></div></TabsContent>
 <TabsContent value="policies"><section className="panel"><div className="panelhead"><h2>Immutable policy versions</h2><Button onClick={()=>open('publish_policy')}><Plus size={15}/>Publish policy</Button></div><Table><TableHeader><TableRow><TableHead>Version</TableHead><TableHead>Policy</TableHead><TableHead>Organization</TableHead><TableHead>Published</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data?.policies.map(p=><TableRow key={p.id}><TableCell><code>{p.id}</code></TableCell><TableCell><strong>{p.title}</strong><details><summary>Read policy</summary><p>{p.text}</p><code>{p.text_sha256}</code><p><a href={safeLink(p.source_url)} target="_blank" rel="noreferrer">Public reference <ExternalLink size={13}/></a></p></details></TableCell><TableCell>{org(p.organization_id)?.name}</TableCell><TableCell>{stamp(p.published_at)}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>open('open_compliance_check',{policy_id:p.id})}>Open check</Button></TableCell></TableRow>)}</TableBody></Table>{!data?.policies.length&&<div className="empty">No policies to display.</div>}</section></TabsContent>
 <TabsContent value="organizations"><section className="panel"><div className="panelhead"><h2>Organization register</h2><Button onClick={()=>open('create_organization')}>Register organization</Button></div><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Organization</TableHead><TableHead>Owner</TableHead><TableHead>Identity</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data?.organizations.map(o=><TableRow key={o.id}><TableCell><code>{o.id}</code></TableCell><TableCell><strong>{o.name}</strong><p><a href={safeLink(o.website)} target="_blank" rel="noreferrer">Website <ExternalLink size={13}/></a></p></TableCell><TableCell><code>{short(o.owner)}</code></TableCell><TableCell><span className="badge">SELF DECLARED</span></TableCell><TableCell><Button size="sm" variant="outline" disabled={sender!==o.owner} onClick={()=>open('publish_policy',{organization_id:o.id})}>Publish policy</Button></TableCell></TableRow>)}</TableBody></Table>{!data?.organizations.length&&<div className="empty">No organizations to display.</div>}</section></TabsContent>
 <TabsContent value="transactions"><section className="panel"><div className="panelhead"><h2>Your transactions</h2><span className="hint">Saved on this browser</span></div><Table><TableHeader><TableRow><TableHead>Action</TableHead><TableHead>Transaction</TableHead><TableHead>Status</TableHead><TableHead>Receipt</TableHead></TableRow></TableHeader><TableBody>{txs.map(t=><TableRow key={t.hash}><TableCell>{label(t.method)}</TableCell><TableCell><a href={deployment.explorer+'/transactions/'+t.hash} target="_blank" rel="noreferrer"><code>{short(t.hash)}</code> <ExternalLink size={13}/></a><small>{new Date(t.time).toLocaleString()}</small></TableCell><TableCell><span className={'badge '+(t.status==='FINALIZED'?'final':'')}>{label(t.status)}</span>{t.error&&<p className="failure">{t.error}</p>}</TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>recheck(t)}>Recheck receipt</Button></TableCell></TableRow>)}</TableBody></Table>{!txs.length&&<div className="empty">No transactions submitted from this browser yet.</div>}</section></TabsContent></Tabs>
 <footer className="foot"><div><ShieldCheck size={18}/><span>Attestations apply to one policy version and scope. They are not legal certifications.</span></div><div><a href={deployment.explorer+'/address/'+deployment.address} target="_blank" rel="noreferrer">Contract {short(deployment.address)} <ExternalLink size={13}/></a><a href={deployment.studio} target="_blank" rel="noreferrer">GenLayer Studio <ExternalLink size={13}/></a></div><p>Studionet is a resettable development network. The demo organization and incident are fictional. No real funds or external wallet connection are used.</p></footer>
 <Dialog open={senderOpen} onOpenChange={setSenderOpen}><DialogContent><DialogHeader><DialogTitle>Studio development account</DialogTitle><DialogDescription>Use your built-in GenLayer Studio address or generate a fresh development sender. No external wallet connection is required.</DialogDescription></DialogHeader><label htmlFor="sender">Studio address</label><Input id="sender" placeholder="0x…" value={senderInput} onChange={e=>setSenderInput(e.target.value)}/><Button onClick={()=>selectSender(senderInput)}>Use Studio address</Button><Button variant="outline" onClick={generate}>Generate demo account</Button><p className="hint">Studionet simulator addresses are development senders. They do not authenticate a production identity or establish domain ownership.</p><a href={deployment.studio} target="_blank" rel="noreferrer">Open GenLayer Studio <ExternalLink size={13}/></a></DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction(null)}}><DialogContent className="actiondialog"><DialogHeader><DialogTitle>{action?.title}</DialogTitle><DialogDescription>{action?.help}</DialogDescription></DialogHeader><Select value={action?.method} onValueChange={v=>setAction(actions.find(a=>a.method===v)!)}><SelectTrigger aria-label="Transaction action"><SelectValue/></SelectTrigger><SelectContent>{actions.map(a=><SelectItem key={a.method} value={a.method}>{a.title}</SelectItem>)}</SelectContent></Select><form onSubmit={submit}>{action?.fields.map(f=><div className="field" key={f}><label htmlFor={f}>{f==='expected_hash'?'Expected SHA256 of rendered text (optional)':label(f)}</label>{longFields.includes(f)?<Textarea rows={4} id={f} value={fields[f]||''} required maxLength={limits[f]||80} onChange={e=>setFields({...fields,[f]:e.target.value})}/>:<Input id={f} value={fields[f]||''} required={f!=='expected_hash'} maxLength={limits[f]||80} placeholder={['website','policy_url','source_url'].includes(f)?'https://…':f==='expected_hash'?'64 lowercase hexadecimal characters':''} onChange={e=>setFields({...fields,[f]:e.target.value})}/>}</div>)}<p className="hint">Sender: {sender||'Choose a Studio development account'}</p>{!gate.enabled&&<p className="failure" role="alert">{gate.reason}</p>}<div className="formbuttons"><Button type="submit" disabled={busy||!gate.enabled}>{busy?'Awaiting finalized receipt…':sender?'Send through GenLayer':'Select Studio account'}</Button><Button type="button" variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify({address:deployment.address,method:action?.method,args:action?.fields.map(f=>fields[f]||'')},null,2));toast.success('Studio arguments copied')}catch{toast.error('Clipboard unavailable')}}}><Copy size={14}/>Copy arguments</Button></div></form></DialogContent></Dialog>
 </main>
}
