export type Action={method:string;title:string;help:string;fields:string[]};
export const actions:Action[]=[
{method:'create_organization',title:'Register organization',help:'The submitting Studio account owns this self-declared registration.',fields:['name','website']},
{method:'publish_policy',title:'Publish policy version',help:'Only the organization owner may publish. Each version is immutable.',fields:['organization_id','title','policy_text','policy_url']},
{method:'open_compliance_check',title:'Open compliance check',help:'Specify the event and period to review. Evidence stays open for 5 minutes.',fields:['policy_id','scope']},
{method:'submit_evidence',title:'Submit evidence',help:'Only check parties can submit. Each side has four reserved initial slots.',fields:['check_id','source_url','statement','expected_hash']},
{method:'submit_response',title:'Organization response',help:'Only the organization owner may respond, using its reserved evidence capacity.',fields:['check_id','response','source_url','expected_hash']},
{method:'validator_review',title:'Validator review',help:'After the submission deadline, validators independently fetch evidence and interpret the policy.',fields:['check_id']},
{method:'challenge',title:'Challenge verdict',help:'One challenge round per check. Add a new evidence URL before the fixed challenge deadline.',fields:['check_id','reason','source_url','expected_hash']},
{method:'submit_counter_evidence',title:'Counter-evidence',help:'During a challenge, each side has two additional reserved slots.',fields:['check_id','source_url','statement','expected_hash']},
{method:'finalize',title:'Finalize check',help:'After the challenge period, COMPLIANT issues an attestation. Other outcomes record a violation or unresolved check.',fields:['check_id']},
{method:'resolve_timeout',title:'Close expired check',help:'After the 24-hour resolution deadline, anyone can close an unfinished check without attestation.',fields:['check_id']}];
export function available(method:string,c:any,sender:string,now:number){if(!c)return{enabled:true,reason:''};const party=[c.owner,c.requester].includes(sender.toLowerCase());const open=c.status==='EVIDENCE_OPEN'&&now<c.evidence_deadline;const reviewed=['REVIEWED','EVIDENCE_REVIEW'].includes(c.status);const states:Record<string,boolean>={submit_evidence:open&&party,submit_response:open&&sender.toLowerCase()===c.owner&&!c.response,validator_review:['EVIDENCE_OPEN','EVIDENCE_REVIEW','CHALLENGED'].includes(c.status)&&now>=(c.status==='CHALLENGED'?c.challenge_deadline:c.evidence_deadline)&&now+120<c.expires_at,challenge:reviewed&&party&&!c.challenged&&now<c.challenge_deadline,submit_counter_evidence:c.status==='CHALLENGED'&&party&&now<c.challenge_deadline,finalize:reviewed&&now>=c.challenge_deadline&&now<c.expires_at,resolve_timeout:!['FINALIZED','EXPIRED'].includes(c.status)&&now>=c.expires_at};return{enabled:states[method]??true,reason:'The required account, state, or deadline condition is not met.'}}
